spring:
  application:
    name: go_logistics_backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

otp:
  expiration-minutes: ${OTP_EXPIRATION_MINUTES}
  max-attempts: ${OTP_MAX_ATTEMPTS}
aws:
  region: ${AWS_REGION}
ses:
  sender-email: ${AWS_SES_SENDER_EMAIL}  

management:
  endpoints:
    web:
      exposure:
        include: health,info
    health:
      show-details: never      