import jsPDF from "jspdf";

export interface QuotePdfData {
  id: string;
  customerName?: string;
  customerEmail?: string;
  origin: string;
  destination: string;
  cargo: string;
  weight: string;
  containerSize: string;
  vehicle: string;
  price: string;
  requestedDate: string;
  status: string;
}

export function downloadQuotePdf(quote: QuotePdfData) {
  const doc = new jsPDF();

  const left = 20;
  let y = 20;

  // Header
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("FASTLY", left, y);

  y += 10;

  doc.setFontSize(16);
  doc.text("Transportation Quote", left, y);

  y += 12;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");

  doc.text(`Quote ID: ${quote.id}`, left, y);
  y += 7;

  doc.text(`Date: ${quote.requestedDate}`, left, y);
  y += 7;

  doc.text(`Status: ${quote.status}`, left, y);

  // Customer
  y += 12;

  doc.setFont("helvetica", "bold");
  doc.text("Customer Details", left, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  if (quote.customerName) {
    doc.text(`Name: ${quote.customerName}`, left, y);
    y += 7;
  }

  if (quote.customerEmail) {
    doc.text(`Email: ${quote.customerEmail}`, left, y);
    y += 7;
  }

  // Route
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text("Route", left, y);

  y += 8;

  doc.setFont("helvetica", "normal");
  doc.text(`Origin: ${quote.origin}`, left, y);
  y += 7;

  doc.text(`Destination: ${quote.destination}`, left, y);

  // Cargo
  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("Cargo Details", left, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  doc.text(`Cargo: ${quote.cargo}`, left, y);
  y += 7;

  doc.text(`Weight: ${quote.weight}`, left, y);
  y += 7;

  doc.text(
    `Container Size: ${quote.containerSize}`,
    left,
    y,
  );

  // Transportation
  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("Transportation", left, y);

  y += 8;

  doc.setFont("helvetica", "normal");

  doc.text(`Vehicle: ${quote.vehicle}`, left, y);

  // Price
  y += 15;

  doc.setFont("helvetica", "bold");
  doc.text("Quoted Price", left, y);

  y += 10;

  doc.setFontSize(16);
  doc.text(quote.price, left, y);

  // Footer
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");

  doc.text(
    "Generated by FASTLY Transportation",
    left,
    285,
  );

  doc.save(`FASTLY-${quote.id}.pdf`);
}